apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: withastro-github-comment-templates
    namespace: withastro-github-comment-templates
spec:
    secretName: withastro-github-comment-templates
    issuerRef:
        name: acme-issuer
        kind: ClusterIssuer
    dnsNames:
        - "withastro-github-comment-templates.trueberryless.org"
